### ISSUE TITLE
FileNotFoundException when using the wrapper

### ISSUE THREAD

**Issue by code-SL** [LiYouBioinfo/DELTA-Toolkit#2]
After reaching the Reading Library Files step, the following error is generated.  Any guidance would be appreciated.

Upon `java -jar /home/user/Downloads/DELTA_hitgen/DEL_AnalysisToolkit_NAR.jar project -proj S1_2023011114`, after having run `java -jar /home/user/Downloads/DELTA_hitgen/DEL_AnalysisToolkit_NAR.jar prep -f run_1.spapb -o ./ -s S1`, the following traceback:

```
Use Old Project Summary Directory: /mnt/T7/S1_2023011114/Analysis/ProjectSummary_202301111444/
[2023/01/11 14:56:41]	Writing all downstream commands into /mnt/T7/S1_2023011114/Analysis/ProjectSummary_202301111444/runScenario.sh
[2023/01/11 14:56:41]	Reading library files.	
java.io.FileNotFoundException:  (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at DEL_AnalysisToolkit.DEL_ReferenceFiles.constructHashes(DEL_ReferenceFiles.java:1044)
	at DEL_AnalysisToolkit.DEL_ProjectWrapper.runBuilder(DEL_ProjectWrapper.java:872)
	at DEL_AnalysisToolkit.DEL_ProjectWrapper.analysisStart(DEL_ProjectWrapper.java:531)
	at DEL_AnalysisToolkit.DEL_ProjectWrapper.runProjectWrapper(DEL_ProjectWrapper.java:504)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:20)
```

**Comment by LiYouBioinfo** [comment]
Hi. From the error message, it seems that the toolkit is complaining a missing file that contains the dictionary for all the DEL structure files. You may go to this link [wiki page](https://github.com/LiYouBioinfo/DELTA-Toolkit/wiki/run-as-an-integrated-pipeline#prepare-del-structure-files) and follow the instructions under the **Prepare DEL structure files** section.
