### ISSUE TITLE
grouping step

### ISSUE THREAD

**Issue by rcdash** [LiYouBioinfo/DELTA-Toolkit#4]
Hi facing a issue in grouping step. Any suggestion?

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

**Comment by LiYouBioinfo** [comment]
Hi. For your -ctrl option, you need to specify tag type like ***@***.*** If you are not sure about the tag type, you can write something like -ctrl ***@***.*** Let me know if it resolves the problem.

 

Cheers

You Li (Lynn), Ph.D | 李游博士

Director of NGS and Bioinformatics | 测序与生物信息学总监

Lead Generation Unit | 先导化合物发现中心

 

 

HitGen Inc. | 成都先导药物开发股份有限公司

Building 6, Tianfu International Bio-Town,

No.8, Huigu 1st East Road, Shuangliu District, 

Chengdu, Sichuan, China, 610000

中国四川成都市双流区（天府国际生物城）慧谷东一路8号6栋

O: +86-28-85197385-8215 | E:  ***@***.***> ***@***.***

 

发件人: rcdash ***@***.***> 
发送时间: 2024年7月26日 20:49
收件人: LiYouBioinfo/DELTA-Toolkit ***@***.***>
抄送: Subscribed ***@***.***>
主题: [EXTERNAL][LiYouBioinfo/DELTA-Toolkit] grouping step (Issue #4)

 

Hi facing a issue in grouping step. Any suggestion?

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

**Comment by rcdash** [comment]
Hi LiYou,
Thanks for quick reply.
S5 is bead alone

i tried 
-ctrl ***@***.***
error: [ERROR]: Sample abbreviation ***.*** specified in -ctrl option could not be found in the -G option 
Step grouping does not exit properly. Exit

when -ctrl ***@S5
[2024/07/26 10:12:08]	Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
	at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

**Comment by rcdash** [comment]
I tried -ctrl ***@***.***
[ERROR]: Sample abbreviation ***.*** specified in -ctrl option could not be found in the -G option 
Step grouping does not exit properly. Exit

**Comment by rcdash** [comment]
I tried -ctrl ***@***.***
[ERROR]: Sample abbreviation . specified in -ctrl option could not be found in the -G option
Step grouping does not exit properly. Exit

**Comment by LiYouBioinfo** [comment]
Hi. In your previous command, you were writing 

 

java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/



 

so you need to change “-ctrl S5” to “-ctrl ***@***.***”, following the format of [bead ***@***.*** abbreviation].

 

I am not sure what you have written in your previous email, because I see -ctrl @.***. None of the string matches with the -G tag (S1:S3:S5).

 

Best

You Li (Lynn), Ph.D | 李游博士

Director of NGS and Bioinformatics | 测序与生物信息学总监

Lead Generation Unit | 先导化合物发现中心

 

 

HitGen Inc. | 成都先导药物开发股份有限公司

Building 6, Tianfu International Bio-Town,

No.8, Huigu 1st East Road, Shuangliu District, 

Chengdu, Sichuan, China, 610000

中国四川成都市双流区（天府国际生物城）慧谷东一路8号6栋

O: +86-28-85197385-8215 | E:  ***@***.***> ***@***.***

 

发件人: rcdash ***@***.***> 
发送时间: 2024年7月26日 22:19
收件人: LiYouBioinfo/DELTA-Toolkit ***@***.***>
抄送: LiYouBioinfo ***@***.***>; Comment ***@***.***>
主题: [EXTERNAL]Re: [LiYouBioinfo/DELTA-Toolkit] grouping step (Issue #4)

 

I tried -ctrl @.***
[ERROR]: Sample abbreviation . specified in -ctrl option could not be found in the -G option
Step grouping does not exit properly. Exit

**Comment by rcdash** [comment]
S1 and S3 are my samples and S5 is bead
this is my spa file
Sample1	/data/HG135/sample1/fastq/	S1
Sample3	/data/HG135/sample3/fastq/	S3
Sample5	/data/HG135/sample5/fastq/	S5

I tried different option in -ctrl as per your suggestion

java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl ***@S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
[2024/07/26 10:51:37]	Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
	at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl bead ***@***.*** -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl bead@S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
[2024/07/26 10:54:37]	Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
	at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
	at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
	at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

**Comment by LiYouBioinfo** [comment]
Hi. Only the last command is correct in terms of the -ctrl tag. And you can also see the error is different from the previous commands. For the new error you received, there should be some discrepancies about the DEL name you specified in your BB-Codon list.  Are you using HitGen’s OpenDEL? If not, can I see the BB-codon structure file and also the enriched feature file under  /data/HG135/rcd135_2024072515/Analysis/Sample3_out/Features/

 

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl ***@***.*** -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
[2024/07/26 10:54:37] Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

 

Cheers

You Li (Lynn), Ph.D | 李游博士

Director of NGS and Bioinformatics | 测序与生物信息学总监

Lead Generation Unit | 先导化合物发现中心

 

 

HitGen Inc. | 成都先导药物开发股份有限公司

Building 6, Tianfu International Bio-Town,

No.8, Huigu 1st East Road, Shuangliu District, 

Chengdu, Sichuan, China, 610000

中国四川成都市双流区（天府国际生物城）慧谷东一路8号6栋

O: +86-28-85197385-8215 | E:  ***@***.***> ***@***.***

 

发件人: rcdash ***@***.***> 
发送时间: 2024年7月26日 22:57
收件人: LiYouBioinfo/DELTA-Toolkit ***@***.***>
抄送: LiYouBioinfo ***@***.***>; Comment ***@***.***>
主题: [EXTERNAL]Re: [LiYouBioinfo/DELTA-Toolkit] grouping step (Issue #4)

 

S1 and S3 are my samples and S5 is bead
this is my spa file
Sample1 /data/HG135/sample1/fastq/ S1
Sample3 /data/HG135/sample3/fastq/ S3
Sample5 /data/HG135/sample5/fastq/ S5

I tried different option in -ctrl as per your suggestion

java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl S5 -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl ***@***.*** <https://github.com/s5>  -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
[2024/07/26 10:51:37] Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl bead @.*** -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
at DEL_AnalysisToolkit.DEL_SampleGrouping.createOptions(DEL_SampleGrouping.java:647)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:43)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

Running grouping. Command line:
java -jar /data/HG135/DEL_AnalysisToolkit_NAR_20230215.jar grouping -ctrl ***@***.*** -G S1:S3:S5 -S /data/HG135/rcd135_2024072515/Analysis/Sample1_out/:/data/HG135/rcd135_2024072515/Analysis/Sample3_out/:/data/HG135/rcd135_2024072515/Analysis/Sample5_out/ -outdir /data/HG135/rcd135_2024072515/Analysis/ProjectSummary_202407251508/
Option -home not given. Infer the home from the first path in -S option.
Option -ref not given. Infer the home from the first path in -S option.
[2024/07/26 10:54:37] Merge PolyO score
Loading BB-0-OpenDEL0001
Exception in thread "main" java.lang.NullPointerException
at DEL_AnalysisToolkit.Utils.Group_FileDescriptor.writeToLocalFile(Group_FileDescriptor.java:308)
at DEL_AnalysisToolkit.DEL_SampleGrouping.loadRecordByDELs(DEL_SampleGrouping.java:260)
at DEL_AnalysisToolkit.DEL_SampleGrouping.runGrouping(DEL_SampleGrouping.java:47)
at DEL_AnalysisToolkit.DEL_AnalysisToolkit.main(DEL_AnalysisToolkit.java:41)
Step grouping does not exit properly. Exit

**Comment by rcdash** [comment]
HI You Li,
I am using HitGen’s OpenDEL. Please find the attachment of the files.

[fullcpdPolyO.txt](https://github.com/user-attachments/files/16393617/fullcpdPolyO.txt)
[features.significant.expanded.txt](https://github.com/user-attachments/files/16393618/features.significant.expanded.txt)
[features.log](https://github.com/user-attachments/files/16393619/features.log)

**Comment by LiYouBioinfo** [comment]
Hi. Thanks for using HitGen’s OpenDEL. I have some troubles accessing the files you pasted (I guess it is some DNS issue with Github for IPs from China). If it is OK, can we schedule a quick call earlier next week to go through all the questions you might have? Also, you may send emails to the following email address for a more direct contact. Thanks.

 

My email account is you.li, and the domain is hitgen.com (guess github will block the email automatically. So let me know if you are not able to see it).

you.li at hitgen.com

 

Cheers

You Li (Lynn), Ph.D | 李游博士

Director of NGS and Bioinformatics | 测序与生物信息学总监

Lead Generation Unit | 先导化合物发现中心

 

 

HitGen Inc. | 成都先导药物开发股份有限公司

Building 6, Tianfu International Bio-Town,

No.8, Huigu 1st East Road, Shuangliu District, 

Chengdu, Sichuan, China, 610000

中国四川成都市双流区（天府国际生物城）慧谷东一路8号6栋

O: +86-28-85197385-8215 | E:  ***@***.***> ***@***.***

 

发件人: rcdash ***@***.***> 
发送时间: 2024年7月26日 23:24
收件人: LiYouBioinfo/DELTA-Toolkit ***@***.***>
抄送: LiYouBioinfo ***@***.***>; Comment ***@***.***>
主题: [EXTERNAL]Re: [LiYouBioinfo/DELTA-Toolkit] grouping step (Issue #4)

 

HI You Li,
I am using HitGen’s OpenDEL. Please find the attachment of the files.

fullcpdPolyO.txt <https://github.com/user-attachments/files/16393617/fullcpdPolyO.txt> 
features.significant.expanded.txt <https://github.com/user-attachments/files/16393618/features.significant.expanded.txt> 
features.log <https://github.com/user-attachments/files/16393619/features.log>

**Comment by rcdash** [comment]
My email id radhacharan.dash@einsteinmed.edu. I have just forwarded the files from my academic email.
